# This is a basic workflow to help you get started with Actions
name: Flutter Analyze and Build CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# if wanting to make releases
permissions:
  contents: write

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: flutter build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build linux --debug
      - run: flutter build linux --release
#      - run: flutter test
      - uses: actions/upload-artifact@v4
        with:
          name: DebugBuild
          path: "build/linux/x64/debug/bundle/"
          retention-days: 14
      - uses: actions/upload-artifact@v4
        with:
          name: ReleaseBuild
          path: "build/linux/x64/release/bundle/"
          retention-days: 14
